# title: My Awesome Site
# description: >-  # 这意味着在遇到 "baseurl:" 之前忽略换行符
#   This is my awesome site built with Jekyll and GitHub Pages.
# baseurl: "" # 你站点的子路径，例如 /blog
# url: "https://Xiaohuzi-design.github.io" # 你站点的基本主机名和协议
# theme: jekyll-theme-minimal


title: 机械仔的探索世界
logo: "/assets/img/机器人.png"  # 可放置一个机器人或机械风格的logo图像
description: >-
  欢迎来到机械仔的个人网站！这里记录了我的机器人技术、机器视觉、深度学习以及更多的技术探索。
show_downloads: true
google_analytics:    # 你的 Google Analytics 跟踪 ID
baseurl: ""  # 如果有子路径，例如 /blog
url: "https://Xiaohuzi-design.github.io"  # 站点的基础链接
theme: jekyll-theme-minimal
#remote_theme: pages-themes/minimal@v0.2.0

# 自定义设置
author:
  name: 机械仔
  email: xiaohuzi@example.com

# 配色方案
colors:
  primary: "#1F2A44" # 深蓝色
  secondary: "#FF6347" # 番茄红


# 网站功能增强
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# 网站的元数据
social_links:
  twitter: https://twitter.com/Xiaohuzi
  github: https://github.com/Xiaohuzi-design
  linkedin: https://www.linkedin.com/in/xiaohuzi


# 导航栏配置
navigation:
  - title: 首页
    url: /
  - title: 博客
    url: /blog/
  - title: 项目
    url: /projects/
  - title: 关于
    url: /about/
  - title: 联系
    url: /contact/
  - title: Libra项目
    url: /libra/
