# title: My Awesome Site
# description: >-  # 这意味着在遇到 "baseurl:" 之前忽略换行符
#   This is my awesome site built with Jekyll and GitHub Pages.
# baseurl: "" # 你站点的子路径，例如 /blog
# url: "https://Xiaohuzi-design.github.io" # 你站点的基本主机名和协议
# theme: jekyll-theme-minimal


title: 机械仔的探索世界
logo: "/assets/img/机器人.png"  # 可放置一个机器人或机械风格的logo图像
description: >-
  欢迎来到机械仔的个人网站！这里记录了我的机器人技术、机器视觉、深度学习以及更多的技术探索。
show_downloads: true
google_analytics:    # 流量分析工具，你的Google Analytics跟踪ID ，类似UA-XXXXXXXX-X
baseurl: ""  # 如果有子路径，例如 /blog
url: "https://Xiaohuzi-design.github.io"  # 站点的基础链接
theme: jekyll-theme-minimal     # 本地主体
#remote_theme: pages-themes/minimal@v0.2.0  # 远程主题


# 网站功能增强
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# 覆盖 GitHub 生成的 URL
github:
  # github下载格式 https://github.com/{owner}/{repository}/archive/refs/heads/{branch}.zip
  zip_url: https://github.com/pages-themes/minimal/archive/refs/heads/main.zip
  tar_url: https://github.com/pages-themes/minimal/archive/refs/heads/main.tar.gz
  repository_url: https://Xiaohuzi-design.github.io
  another_url: another value

# 社交链接
social_links:
  douyin: https://www.douyin.com/yourprofile
  bilibili: https://space.bilibili.com/yourprofile
  youtube: https://www.youtube.com/channel/yourprofile

# 配色方案
colors:
  primary: "#1F2A44" # 深蓝色
  secondary: "#FF6347" # 番茄红

# 自定义设置
author:
  name: 机械仔
  email: xiaohuzi@example.com


