title: My Awesome Site
description: >- # this means to ignore newlines until "baseurl:"
  This is my awesome site built with Jekyll and GitHub Pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Xiaohuzi-design.github.io" # the base hostname & protocol for your site
theme: jekyll-theme-minimal
